version: '3.8'

services:
  # разворачиваем сервис-Producer, из приложения simple-producer
  # Docker-image данного приложения был создан и опубликован в локальный docker-registry
  producer:
    image: kafka-producer:1.0
    environment:
      # Указываем порт к kafka_first, в развернутом кластере
      # Порт можно увидеть в конфигурации кластера (docker-cluster.yml) в переменной KAFKA_ADVERTISED_LISTENERS
      - BROKER=kafka_first:19091

  # разворачиваем сервис-Consumer, из приложения simple-producer
  # Docker-image данного приложения был создан и опубликован в локальный docker-registry
  consumer:
    image: kafka-consumer:1.0
    environment:
      - BROKER=kafka_second:19092
      # передаем значение задержки времени обработки сообщения
      # это нужно для имиитации того, что Consumer медленнее обрабатывает сообщения, чем их
      # производит Producer
      - MESSAGE_PROCESSING_TIME=2000
    depends_on:
      - producer